version: '2'

services:
  server-backend:
    depends_on: [ server-mysql ]
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/app
    ports:
    - "8000:8000"

    environment:
      DB_NAME: sql_db
      DB_HOST: server-mysql
      DB_USER: sql_user
      DB_PASSWORD: sql_pass

  server-mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - .sql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sql_root_pass
      MYSQL_DATABASE: sql_db
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: sql_pass

  server-centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo -c /centrifugo/centrifugo.json --admin
    volumes:
    - ./config/centrifugo.json:/centrifugo/centrifugo.json
    restart: always
    ports:
    - 9000:9000

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  server-nginx:
    image: nginx:latest
    restart: always
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf
    expose:
    - 8080
    ports:
    - 80:8080
    depends_on: [ server-backend ]
    links:
    - server-backend
    - server-centrifugo
