# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180318_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='data',
            field=models.TextField(null=True, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435 \u0432\u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
