# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_auto_20180514_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Like')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questions.Question', verbose_name='Likes')),
            ],
        ),
    ]
