# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-16 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20180529_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_mime', models.CharField(max_length=72)),
                ('file_key', models.CharField(max_length=72)),
                ('file_content', models.FileField(null=True, upload_to='files')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.FileField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.ManyToManyField(to='questions.QuestionFile'),
        ),
    ]
